// preact-app/src/pages/Store/index.tsx
import { useEffect, useState } from "preact/hooks";
import "./style.css";
import { useLocation } from "preact-iso";
import { getAllProducts } from "../../api";

export function Store() {
  const { route } = useLocation();

  const navigateToItem = (itemId) => {
    route(`/store/${itemId}`);
  };

  const [products, setProducts] = useState([]);
  useEffect(() => {
    const fetchProducts = async () => {
      const products = await getAllProducts();
      setProducts(products);
    };

    fetchProducts();
  }, []);
  return (
    <div class="storeContainer">
      {products.map((item, index) => (
        <div key={index} class="productCard">
          <h1>{item.name}</h1>
          <img src={item.image} alt={item.name} class="itemPhoto" />
          <div class="buttons">
            <button onClick={() => navigateToItem(item.id)}>
              Read more...
            </button>
            <button>Add to cart for {item.price}€</button>
          </div>
        </div>
      ))}
    </div>
  );
}

function Resource(props) {
  return (
    <a href={props.href} target="_blank" class="resource">
      <h2>{props.title}</h2>
      <p>{props.description}</p>
    </a>
  );
}

// svelte-app/src/routes/store/+page.svelte
<script lang="ts">
	import type { Product } from './+page.server';
	interface Data {
		products: Product[];
	}
	export let data: Data;
</script>

<div class="storeContainer">
	{#each data.products as product (product.id)}
		<div class="productCard">
			<h1>{product.name}</h1>
			<img src={product.image} alt={product.name} class="itemPhoto" />

			<div class="buttons">
				<a href="store/{product.id}">
					<button>Read more..</button>
				</a>
				<button>Add to cart for {product.price}€</button>
			</div>
		</div>
	{/each}
</div>

<svelte:head>
	<title>Store</title>
	<meta name="description" content="Store including all products" />
</svelte:head>

<style>
	.storeContainer {
		display: flex;
		flex-wrap: wrap;
		gap: 1rem;
		justify-content: center;
		padding: 2rem 0;
	}
	.productCard {
		background-color: var(--bgSoft);
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 1rem;
		margin: 1rem;
		border-radius: 1rem;
		padding: 1.5rem;
		max-width: 50%;
	}
	.itemPhoto {
		object-fit: cover;
		border-radius: 1rem;
		width: 400px;
		height: auto;
	}
	.buttons {
		display: flex;
		justify-content: center;
		gap: 1rem;
	}
	@media (max-width: 60rem) {
		.buttons {
			display: flex;
			justify-content: center;
			gap: 1rem;
			flex-direction: column;
		}
	}
</style>
