// angular-app/src/app/store/store.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../services/api.service';
import { IProduct } from '../../types';
import { RouterModule } from '@angular/router';
import { CommonModule, NgFor } from '@angular/common';

@Component({
  selector: 'app-store',
  standalone: true,
  imports: [RouterModule, CommonModule],
  templateUrl: './store.component.html',
  styleUrl: './store.component.scss'
})
export class StoreComponent {
  products: IProduct[] = [];
  constructor(private apiService: ApiService) {
  }

  fetchProducts() {
    this.apiService.getAllProducts().subscribe(response => {
      this.products = response;
    });
  }
  
  ngOnInit() {
    this.fetchProducts();
  }

  
}

<div class="storeContainer">
  <div *ngFor="let item of products; let i = index" class="productCard">
    <h1>{{ item.name }}</h1>
    <img
      src="{{ item.image }}"
      alt="{{ item.name }}"
      width="300"
      height="400"
      class="itemPhoto"
    />
    <div class="buttons">
      <a [routerLink]="['/store', item.id]"><button>Read more..</button></a>
      <button>Add to cart for {{ item.price }}€</button>
    </div>
  </div>
</div>

// csr-react/src/Store/Store.jsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./style.css";
import { getAllProducts } from "../api";
import { Button } from "../components/Button/Button";
export function Store() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    const fetchProducts = async () => {
      var items = await getAllProducts();
      setProducts(items || []); // Fallback to an empty array if null is returned
    };

    fetchProducts();
  }, []);

  return (
    <div className="storeContainer">
      {products.map((item, index) => (
        <div key={index} className="productCard">
          <h1>{item.name}</h1>
          <img
            src={`${process.env.REACT_APP_URL}/${item.image}`}
            alt={item.name}
            className="itemPhoto"
          />
          <div className="buttons">
            <Button label={"Read more..."} path={`/store/${item.id}`}></Button>
            <button>Add to cart for {item.price}€</button>
          </div>
        </div>
      ))}
    </div>
  );
}
