// next_js_app/src/components/navbar/links/Links.tsx
"use client";
import { useState } from "react";
import styles from "./links.module.css";
import NavLink from "./navLink/navLink";
import { Links as LinksList } from "@/app/models/models";
import Image from "next/image";

const Links = () => {
  const [open, setOpen] = useState(false);
  return (
    <div className={styles.container}>
      <div className={styles.links}>
        {LinksList.map((link) => (
          <NavLink item={link} key={link.title} />
        ))}
      </div>
      <button
        className={styles.menuButton}
        onClick={() => setOpen((prev) => !prev)}
      >
        <Image
          src="/menu_hamburger.svg"
          alt="hamburger menu icon"
          width={30}
          height={30}
        ></Image>
      </button>
      {open && (
        <div className={styles.mobileLinks}>
          {LinksList.map((link) => (
            <NavLink item={link} key={link.title}></NavLink>
          ))}
        </div>
      )}
    </div>
  );
};

export default Links;

// angular-app/src/app/layout/navbar/links/links.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-links',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './links.component.html',
  styleUrl: './links.component.scss',
})
export class LinksComponent {
  open = false;
  linksList = ['Home', 'About', 'Store', 'Contact']; // Assuming LinksList is an array of link objects

  toggleOpen(): void {
    this.open = !this.open;
  }
}

<div>
  <div class="links">
    <a routerLink="/" routerLinkActive="active" class="linkButton">Home</a>
    <a routerLink="/about" routerLinkActive="active" class="linkButton"
      >About</a
    >
    <a routerLink="/store" routerLinkActive="active" class="linkButton"
      >Store</a
    >
    <a routerLink="/contact" routerLinkActive="active" class="linkButton"
      >Contact</a
    >
  </div>
  <button class="menuButton" (click)="toggleOpen()">
    <img
      src="/assets/images/menu_hamburger.svg"
      alt="hamburger menu icon"
      width="30"
      height="30"
    />
  </button>
  @if (open) {
    <div class="mobileLinks">
      <a routerLink="/" routerLinkActive="active" class="linkButton">Home</a>
      <a routerLink="/about" routerLinkActive="active" class="linkButton"
        >About</a
      >
      <a routerLink="/store" routerLinkActive="active" class="linkButton"
        >Store</a
      >
      <a routerLink="/contact" routerLinkActive="active" class="linkButton"
        >Contact</a
      >
    </div>
  }
</div>
