// svelte-app/src/routes/about/+page.svelte
<div class="about">
	<h1>About Fashion Beast</h1>
	<div class="card">
		<p>
			Welcome to our fashion store! We offer a wide range of trendy clothing, shoes, and accessories
			for men and women. Our mission is to provide high-quality products that make you look and feel
			confident.
		</p>
		<div>
			<p>
				At Fashion Store, we believe that fashion is a form of self-expression. Whether you're
				looking for casual everyday wear or a statement piece for a special occasion, we've got you
				covered. Our collection includes the latest fashion trends, timeless classics, and
				everything in between.
			</p>
			<p>
				With our user-friendly website and secure checkout process, shopping with us is convenient
				and hassle-free. We also offer fast shipping and excellent customer service to ensure your
				satisfaction.
			</p>
		</div>
		<p>Visit our store today and discover your unique style with Fashion Store!</p>
	</div>
</div>

<style>
	.about {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 2rem;
		margin-top: 5rem;
        min-height: 80vh;
	}
	.card {
		background-color: var(--bgSoft);
		padding: 2rem 3rem;
		border-radius: 1rem;
		max-width: 50%;
	}
	@media (max-width: 60rem) {
		.card {
			max-width: 100%;
		}
	}
</style>

// jet-vdom-web-app/src/components/content/about/index.tsx
/**
 * @license
 * Copyright (c) 2014, 2024, Oracle and/or its affiliates.
 * Licensed under The Universal Permissive License (UPL), Version 1.0
 * as shown at https://oss.oracle.com/licenses/upl/
 * @ignore
 */
import { h } from "preact";
const About = () => {
  return (
    <div class="oj-hybrid-padding">
      <h1>About us</h1>
      <div class="oj-flex oj-sm-justify-content-center">
        <div class="oj-panel oj-flex oj-panel-shadow-sm oj-sm-only-width-4/5 oj-sm-margin-4x oj-sm-padding-12x oj-sm-justify-content-center oj-sm-align-items-center oj-sm-width-3/5">
          <p class="oj-typography-heading-md">Welcome to our fashion store!</p>
          <div>
            <p class="oj-typography-body-xl">
              We offer a wide range of trendy clothing, shoes, and accessories
              for men and women. Our mission is to provide high-quality products
              that make you look and feel confident.
            </p>
            <p class="oj-typography-body-xl">
              At Fashion Store, we believe that fashion is a form of
              self-expression. Whether you're looking for casual everyday wear
              or a statement piece for a special occasion, we've got you
              covered. Our collection includes the latest fashion trends,
              timeless classics, and everything in between.
            </p>
            <p class="oj-typography-body-xl">
              With our user-friendly website and secure checkout process,
              shopping with us is convenient and hassle-free. We also offer fast
              shipping and excellent customer service to ensure your
              satisfaction.
            </p>
          </div>
          <p class="oj-typography-heading-md">
            Visit our store today and discover your unique style with Fashion
            Store!
          </p>
        </div>
      </div>
    </div>
  );
};
export default About;
