// angular-app/src/app/store/store.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../services/api.service';
import { IProduct } from '../../types';
import { RouterModule } from '@angular/router';
import { CommonModule, NgFor } from '@angular/common';
import { environment } from '../../environments/environment';
@Component({
  selector: 'app-store',
  standalone: true,
  imports: [RouterModule, CommonModule],
  templateUrl: './store.component.html',
  styleUrl: './store.component.scss',
})
export class StoreComponent {
  products: IProduct[] = [];
  environment: any = environment;
  constructor(private apiService: ApiService) {}

  fetchProducts() {
    this.apiService.getAllProducts().subscribe((response) => {
      this.products = response;
    });
  }

  ngOnInit() {
    this.fetchProducts();
  }
}

<div class="storeContainer">
  <div *ngFor="let item of products; let i = index" class="productCard">
    <h1>{{ item.name }}</h1>
    <img
      [src]="environment.apiUrl + '/' + item.image"
      alt="{{ item.name }}"
      width="300"
      height="400"
      class="itemPhoto"
    />
    <div class="buttons">
      <a [routerLink]="['/store', item.id]"><button>Read more..</button></a>
      <button>Add to cart for {{ item.price }}€</button>
    </div>
  </div>
</div>

// preact-app/src/pages/Store/index.tsx
import { useEffect, useState } from "preact/hooks";
import "./style.css";
import { useLocation } from "preact-iso";
import { environment, getAllProducts } from "../../api";

export function Store() {
  const { route } = useLocation();

  const navigateToItem = (itemId) => {
    route(`/store/${itemId}`);
  };

  const [products, setProducts] = useState([]);
  useEffect(() => {
    const fetchProducts = async () => {
      const products = await getAllProducts();
      setProducts(products);
    };

    fetchProducts();
  }, []);
  return (
    <div class="storeContainer">
      {products.map((item, index) => (
        <div key={index} class="productCard">
          <h1>{item.name}</h1>
          <img
            src={`${environment.apiUrl}/${item.image}`}
            alt={item.name}
            class="itemPhoto"
          />
          <div class="buttons">
            <button onClick={() => navigateToItem(item.id)}>
              Read more...
            </button>
            <button>Add to cart for {item.price}€</button>
          </div>
        </div>
      ))}
    </div>
  );
}

function Resource(props) {
  return (
    <a href={props.href} target="_blank" class="resource">
      <h2>{props.title}</h2>
      <p>{props.description}</p>
    </a>
  );
}
